// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PapeleriaBaez.Data;

#nullable disable

namespace PapeleriaBaez.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("PapeleriaBaez.Models.AbonoApartado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartadoId");

                    b.ToTable("abonoApartados");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.AbonoDeuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeudaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeudaId");

                    b.ToTable("AbonosDeudas");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Apartado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pagado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apartados");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.ApartadoCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApartadosCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.CanjeUniforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadConjuntos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CanjeUniformes");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarCompra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleApartado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartadoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalleApartados");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleApartadoCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartadoCanjeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaqueteCanjeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenisCanjeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UniformeCanjeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartadoCanjeId");

                    b.HasIndex("PaqueteCanjeId");

                    b.HasIndex("TenisCanjeId");

                    b.HasIndex("UniformeCanjeId");

                    b.ToTable("DetalleApartadosCanjes");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleCanjeUniforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanjeUniformeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroConjunto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pendiente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniformeCanjeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanjeUniformeId");

                    b.HasIndex("UniformeCanjeId");

                    b.ToTable("DetalleCanjeUniformes");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleCompras");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Deuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pagada")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DevolucionClienteCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TenisDevueltoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenisEntregadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoArticulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCambio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UniformeDevueltoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UniformeEntregadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenisDevueltoId");

                    b.HasIndex("TenisEntregadoId");

                    b.HasIndex("UniformeDevueltoId");

                    b.HasIndex("UniformeEntregadoId");

                    b.ToTable("DevolucionesClienteCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DevolucionFabricaCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoReposicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaReposicion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaqueteCanjeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenisCanjeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoArticulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDevolucion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UniformeCanjeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteCanjeId");

                    b.HasIndex("TenisCanjeId");

                    b.HasIndex("UniformeCanjeId");

                    b.ToTable("DevolucionesFabricaCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.PaqueteCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Entregados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroPaquete")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PaquetesCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.TenisCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Entregados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TenisCanjes");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.UniformeCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Entregados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UniformesCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.ValeTenisCanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pendiente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenisCanjeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenisCanjeId");

                    b.ToTable("ValesTenisCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.AbonoApartado", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.Apartado", "Apartado")
                        .WithMany("Abonos")
                        .HasForeignKey("ApartadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartado");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.AbonoDeuda", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.Deuda", "Deuda")
                        .WithMany("Abonos")
                        .HasForeignKey("DeudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deuda");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleApartado", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.Apartado", "Apartado")
                        .WithMany("Detalles")
                        .HasForeignKey("ApartadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PapeleriaBaez.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleApartadoCanje", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.ApartadoCanje", "ApartadoCanje")
                        .WithMany("Detalles")
                        .HasForeignKey("ApartadoCanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PapeleriaBaez.Models.PaqueteCanje", "PaqueteCanje")
                        .WithMany()
                        .HasForeignKey("PaqueteCanjeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PapeleriaBaez.Models.TenisCanje", "TenisCanje")
                        .WithMany()
                        .HasForeignKey("TenisCanjeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PapeleriaBaez.Models.UniformeCanje", "UniformeCanje")
                        .WithMany()
                        .HasForeignKey("UniformeCanjeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApartadoCanje");

                    b.Navigation("PaqueteCanje");

                    b.Navigation("TenisCanje");

                    b.Navigation("UniformeCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleCanjeUniforme", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.CanjeUniforme", "CanjeUniforme")
                        .WithMany("Detalles")
                        .HasForeignKey("CanjeUniformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PapeleriaBaez.Models.UniformeCanje", "UniformeCanje")
                        .WithMany()
                        .HasForeignKey("UniformeCanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanjeUniforme");

                    b.Navigation("UniformeCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleCompra", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PapeleriaBaez.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DetalleVenta", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PapeleriaBaez.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Deuda", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DevolucionClienteCanje", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.TenisCanje", "TenisDevuelto")
                        .WithMany()
                        .HasForeignKey("TenisDevueltoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PapeleriaBaez.Models.TenisCanje", "TenisEntregado")
                        .WithMany()
                        .HasForeignKey("TenisEntregadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PapeleriaBaez.Models.UniformeCanje", "UniformeDevuelto")
                        .WithMany()
                        .HasForeignKey("UniformeDevueltoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PapeleriaBaez.Models.UniformeCanje", "UniformeEntregado")
                        .WithMany()
                        .HasForeignKey("UniformeEntregadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TenisDevuelto");

                    b.Navigation("TenisEntregado");

                    b.Navigation("UniformeDevuelto");

                    b.Navigation("UniformeEntregado");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.DevolucionFabricaCanje", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.PaqueteCanje", "PaqueteCanje")
                        .WithMany()
                        .HasForeignKey("PaqueteCanjeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PapeleriaBaez.Models.TenisCanje", "TenisCanje")
                        .WithMany()
                        .HasForeignKey("TenisCanjeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PapeleriaBaez.Models.UniformeCanje", "UniformeCanje")
                        .WithMany()
                        .HasForeignKey("UniformeCanjeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PaqueteCanje");

                    b.Navigation("TenisCanje");

                    b.Navigation("UniformeCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Producto", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.ValeTenisCanje", b =>
                {
                    b.HasOne("PapeleriaBaez.Models.TenisCanje", "TenisCanje")
                        .WithMany()
                        .HasForeignKey("TenisCanjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TenisCanje");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Apartado", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.ApartadoCanje", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.CanjeUniforme", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Deuda", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("PapeleriaBaez.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
